Repository cardoso/ReduxMovieDB, pull requests merged in 2019-10, with the labels that each got.

#29 [NEW] Localization + Support for Russian
  ReduxMovieDB.xcodeproj/project.pbxproj
  ReduxMovieDB.xcodeproj/xcshareddata/xcschemes/ReduxMovieDB.xcscheme
  ReduxMovieDB/API/TMDB.swift
  ReduxMovieDB/Base.lproj/Main.storyboard
  ReduxMovieDB/Controllers/MovieDetailViewController.swift
  ReduxMovieDB/Controllers/MovieListViewController.swift
  ReduxMovieDB/ViewState/MovieDetailViewState.swift
  ReduxMovieDB/en.lproj/Localizable.strings
  ReduxMovieDB/ru.lproj/Localizable.strings
Labels: :globe_with_meridians: localization, hacktoberfest

#30 Make ViewStates Conform to Equatable
  ReduxMovieDB/ViewState/MovieDetailViewState.swift
  ReduxMovieDB/ViewState/MovieListViewState.swift
Labels: hacktoberfest, ✨ improvement

#31 Update Project
  .travis.yml
  Gemfile.lock
  Podfile
  Podfile.lock
  Pods/Manifest.lock
  Pods/Nuke/README.md
  Pods/Nuke/Sources/DataCache.swift
  Pods/Nuke/Sources/DataLoader.swift
  Pods/Nuke/Sources/ImageCache.swift
  Pods/Nuke/Sources/ImageDecoding.swift
  Pods/Nuke/Sources/ImagePipeline.swift
  Pods/Nuke/Sources/ImagePreheater.swift
  Pods/Nuke/Sources/ImageProcessing.swift
  Pods/Nuke/Sources/ImageRequest.swift
  Pods/Nuke/Sources/ImageTaskMetrics.swift
  Pods/Nuke/Sources/ImageView.swift
  Pods/Nuke/Sources/Internal.swift
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/ReSwift/README.md
  Pods/ReSwift/ReSwift/CoreTypes/Action.swift
  Pods/ReSwift/ReSwift/CoreTypes/DispatchingStoreType.swift
  Pods/ReSwift/ReSwift/CoreTypes/Middleware.swift
  Pods/ReSwift/ReSwift/CoreTypes/Reducer.swift
  Pods/ReSwift/ReSwift/CoreTypes/State.swift
  Pods/ReSwift/ReSwift/CoreTypes/Store.swift
  Pods/ReSwift/ReSwift/CoreTypes/StoreSubscriber.swift
  Pods/ReSwift/ReSwift/CoreTypes/StoreType.swift
  Pods/ReSwift/ReSwift/CoreTypes/Subscription.swift
  Pods/ReSwift/ReSwift/Utils/Assertions.swift
  Pods/ReSwift/ReSwift/Utils/Coding.swift
  Pods/ReSwift/ReSwift/Utils/TypeHelper.swift
  Pods/RxKeyboard/README.md
  Pods/Target Support Files/DifferenceKit/DifferenceKit.xcconfig
  Pods/Target Support Files/Nuke/Nuke-Info.plist
  Pods/Target Support Files/Nuke/Nuke.xcconfig
  Pods/Target Support Files/Pods-ReduxMovieDB/Pods-ReduxMovieDB-frameworks.sh
  Pods/Target Support Files/Pods-ReduxMovieDB/Pods-ReduxMovieDB.debug.xcconfig
  Pods/Target Support Files/Pods-ReduxMovieDB/Pods-ReduxMovieDB.release.xcconfig
  Pods/Target Support Files/Pods-ReduxMovieDBTests/Pods-ReduxMovieDBTests.debug.xcconfig
  Pods/Target Support Files/Pods-ReduxMovieDBTests/Pods-ReduxMovieDBTests.release.xcconfig
  Pods/Target Support Files/ReSwift/ReSwift-Info.plist
  Pods/Target Support Files/ReSwift/ReSwift.xcconfig
  Pods/Target Support Files/ReSwiftThunk/ReSwiftThunk.xcconfig
  Pods/Target Support Files/RxCocoa/RxCocoa.xcconfig
  Pods/Target Support Files/RxKeyboard/RxKeyboard-Info.plist
  Pods/Target Support Files/RxKeyboard/RxKeyboard.xcconfig
  Pods/Target Support Files/RxRelay/RxRelay.xcconfig
  Pods/Target Support Files/RxSwift/RxSwift.xcconfig
  README.md
  ReduxMovieDB.xcodeproj/project.pbxproj
  ReduxMovieDB.xcodeproj/xcshareddata/xcschemes/ReduxMovieDB.xcscheme
  ReduxMovieDB/AppDelegate.swift
  ReduxMovieDB/Controllers/SplitViewController.swift
  ReduxMovieDB/Extensions/UIImageView+MoviePoster.swift
  ReduxMovieDB/Info.plist
  fastlane/Fastfile
Labels: hacktoberfest, ✨ improvement

#35 Fix excessive TMDB requests sent when viewing movie details
  ReduxMovieDB/Actions/MainStateAction.swift
  ReduxMovieDB/Controllers/MovieListViewController.swift
  ReduxMovieDB/Controllers/SplitViewController.swift
  ReduxMovieDB/State/MainState.swift
  ReduxMovieDBTests/State/MainStateTests.swift
Labels: :zap: performance, hacktoberfest
